### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by MechanosG** [gamerpaddy/acf-unofficial-extras#2]
Sometimes when spawning an engine from this addon (for example pasting a dupe with a Pulse Jet engine) this error will spam the console.

[ERROR] addons/acf uex/lua/autorun/acf_extras.lua:309: attempt to call field 'oldThink' (a nil value)
  1. unknown - addons/acf uex/lua/autorun/acf_extras.lua:309

This is starting to lead to servers telling people to not use this mod.  Removing the dupe makes the spam go away and sometimes you can paste without the error triggering.  But it's random and doesn't affect all players on the server at the same time.  Please fix so us aircraft makers can have an ACF engine option.

**Comment by gamerpaddy** [comment]
dont use the github version 
i fucking hate git and never updated it, use the workshop version instead i havent heard of any error reports on this
